### ISSUE TITLE
Did you release 48kHz restoration model?

### ISSUE THREAD

**Issue by youssefabdelm** [SamsungLabs/hifi_plusplus#3]
Hey guys, I've tried to run inference on an audio file of mine but the results were shockingly bad compared to your results here: https://samsunglabs.github.io/FINALLY-page/

Instead of clear crisp audio, I got crispy distortion with barely any improvement over the original audio. I'm guessing I might be doing something wrong with inference but I will say one notable thing: I couldn't install these required libraries from the requirements file: 

```
conda
mkl-fft
mkl-random
mkl-service
```

So I removed them before running inference:

```
!sed -i '/conda/d' requirements.txt
!sed -i '/mkl-fft==1.2.0/d' requirements.txt
!sed -i '/mkl-random==1.1.1/d' requirements.txt
!sed -i '/mkl-service==2.3.0/d' requirements.txt
```

Not sure if that could be relevant or not.

**Comment by AndreevP** [comment]
Hi! Unfortunately, this is a different paper, the source codes for FINALLY will not be released due to company policy
The HiFi++ is expectedly working not well on real audio because it was trained in very narrow academic dataset, it does not generalize well

Sorry!

**Comment by youssefabdelm** [comment]
Hey Pavel, no worries whatsoever, totally understandable. Still, thank you for the mind blowing paper! I might try to reproduce one day.

**Comment by lbdave94** [comment]
I was checking your code since it has been reported as the baseline for FINALLY and I have a curiosity. Why in `SpectralUNet` some convolutions have 513 as output_channel? There is a specific reason? I'm asking since usually we want to work with multiple of 8, (so e.g. 512) and 513 is a strange choice.

E.g.:

```
self.learnable_mel2linspec = norm(nn.Conv1d(80, 513, 1))
[...]
self.post_conv_1d = nn.Sequential(
            norm(nn.Conv1d(513, 128, 1, 1, padding=0)),
        )
[...]
```
